### PR TITLE
Impliment proper argument parsing for the console command

### PR DESCRIPTION
**Pull request by the456gamer**

### CODE REVIEW

**Comment by the456gamer** [comment]
ok, im off to bed

**Comment by the456gamer** [comment]
oh btw, that isnt tested

**Comment by xsmeths** [comment]
can and will test, no problem

**Comment by xsmeths** [comment]
This issue is resolved in master branch, thank you for the Pull Request anyway.

**Comment by the456gamer** [comment]
This is only the server command sender, and I'll rewrite the other Sender too when I get time

**Comment by mrfloris** [comment]
I've tested console: xprate 5 true, it updated config.yml with xprate: 5
i've tested in-game /xprate 4 true, it does not update config.yml 

Please note i've pushed bunch of updates to git, so get that first before tinkering.

**Comment by mrfloris** [comment]
I understand that changes from this pr were added to master, i got master, merged with what i had, and this got closed, find out something doesn't work and this got re-opened. 

What i have local is what i have, i am busy now, ill check tonight what's lever over from all this and take it from there. It seems like an easy fix, but if there's a PR then it's handier to work on changes to that pr before merging in. So we don't get conflicting code changes.  I guess.

ServerCommand.java is fine on my local, it works, tested. It's just player - and 456 said in dm he didnt' do that one, and it's probably trying as /xprate 2 true, to run true as integer when it's bool, so.

**Comment by xsmeths** [comment]
Actually nothing from this pr is in master, I tested the code from this pr and it errored out and didn't save rate to config whether commands were done from console or in-game, that's why I closed it.

**Comment by the456gamer** [comment]
> error
> In console
Do you have a Stack trace of this one? This is the only thing that would have changed, so the stacktrace above is non applicable to console commands

**Comment by xsmeths** [comment]
you are correct, no error, updated comment, worth noting that the code in your pr makes setting the rate from console no longer save to the config correctly, unsure why.

**Comment by the456gamer** [comment]
I'll have a look.  What's the command your using?

**Comment by the456gamer** [comment]
im going to test this now

**Comment by xsmeths** [comment]
👍 looks good 😃

**Comment by xsmeths** [comment]
I see some comments about it being hacky, tbh, bukkit api is just hacky itself :P

**Comment by mrfloris** [comment]
Don't merge this yet, I want to review this thread and I will merge it when I am done.

**Pull request merged**
